server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: interviewcoach
  datasource:
    url: jdbc:postgresql://localhost:5432/interviewcoach
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

app:
  jwt:
    secret: ${JWT_SECRET:c2VjcmV0LWtleS1mb3ItaW50ZXJ2aWV3LWNvYWNoLWFwcC1jaGFuZ2UtaW4tcHJvZHVjdGlvbi1wbGVhc2U=}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  gemini:
    api-key: xxx
    api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
